### ISSUE TITLE
Home brewed fork of MELPA

### ISSUE THREAD

**Issue by CestDiego** [melpa/melpa#4131]
Could I use the code in MELPA to have my own kind of private package archive for computers at my home? given that MELPA doesn't support private repos, I was wondering that maybe I can set up something like that in a private server in network to share packages between devices.

But when I clone the repo and delete all the recipes I get a 

```
 • Updating packages/archive-contents ...
emacs --no-site-file --batch -l package-build/package-build.el --eval '(package-build-dump-archive-contents)'
File: /home/stack/melpa/packages/archive-contents
 • Building html/archive.json ...
emacs --no-site-file --batch -l package-build/package-build.el --eval '(let ((package-build-stable nil) (package-build-archive-dir (expand-file-name "./packages/" package-build--melpa-base))) (package-build-archive-alist-as-json "html/archive.json"))'
 • Building html/recipes.json ...
emacs --no-site-file --batch -l package-build/package-build.el --eval '(let ((package-build-stable nil) (package-build-archive-dir (expand-file-name "./packages/" package-build--melpa-base))) (package-build-recipe-alist-as-json "html/recipes.json"))'
 • Building html index ...
make -C ./html
make[1]: Entering directory `/home/stack/melpa/html'
erb updates.rss.erb > updates.rss.tmp && mv updates.rss.tmp updates.rss
/usr/lib/ruby/1.9.1/json/common.rb:148:in `parse': 746: unexpected token at 'null' (JSON::ParserError)
	from /usr/lib/ruby/1.9.1/json/common.rb:148:in `parse'
	from updates.rss.erb:18:in `<main>'
	from /usr/lib/ruby/1.9.1/erb.rb:838:in `eval'
	from /usr/lib/ruby/1.9.1/erb.rb:838:in `result'
	from /usr/lib/ruby/1.9.1/erb.rb:820:in `run'
	from /usr/bin/erb:133:in `run'
	from /usr/bin/erb:154:in `<main>'
make[1]: *** [updates.rss] Error 1
make[1]: Leaving directory `/home/stack/melpa/html'
make: *** [index] Error 2

```

Any help would be greatly appreciated

**Comment by purcell** [comment]
Yes, the RSS feed generation doesn't work when there are no packages. I'm not really interested in fixing that, sorry. :-)

In any case, you probably don't want all of the MELPA machinery. Perhaps something like `quelpa` is what you're looking for?

**Comment by CestDiego** [comment]
quelpa does work well thanks :)

**Comment by purcell** [comment]
Yay, great! I'll close this for now then.
